### POST DETAILS

POST http://localhost:8080/api/post-details/poll

{
    "creatorId": 101,
    "postId": 1,
    "pollAnswerId": 1
}

###

POST http://localhost:8080/api/post-details/text

{
    "creatorId": 101,
    "postId": 2,
    "text": "test"
}


### POSTS

GET http://localhost:8080/api/posts
Accept: application/json

###

POST http://localhost:8080/api/posts/poll

{
  "createdOn": "2024-01-01",
  "title": "Can we do it???",
  "definition": "???",
  "creatorId": 100,
  "status": "OPEN",
  "type": "POLL",
  "typeInfo": {
    "pollAnswers": [
      {
        "title": "yes"
      },
      {
        "title": "no"
      }
    ]
  }
}

###

POST http://localhost:8080/api/posts/text

{
  "createdOn": "2024-01-01",
  "title": "Can we do it???",
  "definition": "???",
  "creatorId": 100,
  "status": "OPEN",
  "type": "TEXT"
}
###

GET http://localhost:8080/api/posts/1

###

DELETE http://localhost:8080/api/posts/1

###

POST http://localhost:8080/api/posts/1/status/CLOSED

### USER

POST http://localhost:8080/api/users

{
  "username": "Felix",
  "email": "test@gmx.at"
}

###

GET http://localhost:8080/api/users/login/Felix
Accept: application/json

###

GET http://localhost:8080/api/users/101
Accept: application/json

### RELATION

POST http://localhost:8080/api/relations

{
  "reqUserId": 100,
  "targetUserId": 102,
  "relationStatus": "FRIEND"
}

###

GET http://localhost:8080/api/relations/follows/100

###

GET http://localhost:8080/api/relations/friends/102