name: backend
run-name: building maven project
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls -l logic/backend
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - run: java -version
      - name: build java backend
        working-directory: ./logic/backend
        run: | 
          mvn -B package
          ls -l target
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/mything
          asset_name: mything
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release text"